version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          app-name: restock-wizard-api
          filters:
            branches:
              only: main
      - heroku/deploy-via-git:
          app-name: restock-wizard
          filters:
            branches:
              only: main